name    = "Prehistorical Wild"
credits = "Toma400"
url     = "linktr.ee/toma400"
version = "0.1"

description  = '''
Adds prehistorical origin and worldpack to Isle of Ansur.
'''

[requirements] # needs to be at the end to not be buggy
ansur = "<0.4+"
