loc__crystal_field = "Crystal Field"

loc__crystal_field_descr = '''
You found yourself in a dream, unable to wake up. Bright crystals appear before you, and strange creatures look at you from distance.

Cracking sounds seem to be hearable, yet you are sure there is no music playing...
'''
