name    = "Enderman's Journey"
credits = "Toma400"
url     = "linktr.ee/toma400"
version = "0.1"

description  = '''
Adds races from Minecraft to Isle of Ansur.
'''

[requirements] # needs to be at the end to not be buggy
ansur = "<0.4+"
