loc__test = "Desolat Spires"

loc__test_descr = '''
You found yourself on some desert land, and the sun is setting down. You see rocks rising from the ground, and parts of forest before you.
This makes you feel confused, but the night starts worrying you... some weird noises start to be heard.
'''
