name    = "Shooting Stars"
credits = "Toma400"
url     = "linktr.ee/toma400"
version = "0.1"

description  = '''
Adds End's Phantasm as universe you can awake to.
'''

[requirements] # needs to be at the end to not be buggy
ansur = "<0.4+"
